const stands = [
  {atelier:true,
    pro:true,
    gt:false,
    cursus : "Filière Animation",
    nom: "5-207",
    exposant: "Présentation du bac Animation enfants et personnes agées",
    coords: [765,300], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/aepa.html",
  },
   {atelier:true,
    pro:true,
    gt:false,
    cursus : "Filière Animation",
    nom: "5-204",
    exposant: "Présentation du bac Animation enfants et personnes agées",
    coords: [350,300], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/aepa.html",
  },
  {atelier:false,
    pro:false,
    gt:false,
    cursus : "Retour 1er étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [920,520], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan101er.html",
  },
   {
    cursus : "Retour 1er étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [90,520], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan101er.html",
  }
  
];

