const stands = [
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Sciences de la Vie et de la Terre",
    nom: "10-12",
    exposant: "Labo Sciences",
    coords: [580,35], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/svt.html",

  }, 
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Physique-Chimie",
    nom: "10-13",
    exposant: "Labo Sciences",
    coords: [470,40], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/pc.html",

  },
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Fillière Générales et technologique",
    nom: "Permanence 1",
    exposant: "Présentation de la seconde générale et technologique",
    coords: [700,300], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/secondeGT.html",
  },
  {atelier:true,
    pro:true,
    gt:false,
    cursus : "Fillière VENTE",
    nom: "5-01,5-02,5-03 et 5-04",
    exposant: "Présentation du bac professionnel MRC-MCV",
    coords: [810,450], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/vente.html",
  },
  ,
  {atelier:true,
    pro:true,
    gt:false,
    cursus : "Fillière SANITAIRE",
    nom: "5-05,5-09",
    exposant: "Présentation des ateliers sanitaires",
    coords: [200,450], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/soins.html",
  },
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller au 1er étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [350,280], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan101er.html",
  },
  {atelier:false,
    pro:false,
    gt:false,
    cursus : "Retour au niveau -1",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [300,340], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan10moins1.html",
  },
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller vers le Batiment 7",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [385,500], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan7rdc.html",
  }
];

