const stands = [
  { atelier:true,
    pro:false,
    gt:false,
    cursus : "Proposé à tous ",
    nom: "10-01",
    exposant: "Mobilités ERASMUS+",
    coords: [850,200], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/erasmus.html",
  },
   { atelier:true,
    pro:false,
    gt:true,
    cursus : "Spécialité Lycée Général",
    nom: "10-01",
    exposant: "LLCE",
    coords: [800,220], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/llce.html",
  },
  { atelier:true,
    pro:false,
    gt:true,
    cursus : "Bac général et technologique",
    nom: "10-01",
    exposant: "Bac Américain",
    coords: [800,170], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/bacamericain.html",
  },
  { atelier:true,
    pro:false,
    gt:false,
    cursus : "Proposé à tous ",
    nom: "Atrium",
    exposant: "Projet Numérique",
    coords: [200,400], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/projetnumerique.html",
  },
   { atelier:true,
    pro:false,
    gt:true,
    cursus : "Option Bac Général et Technologique",
    nom: "10-02",
    exposant: "Option EPS - Section Escalade",
    coords: [800,80], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/optionEPS-escalade.html",
  },

   { atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller à l'étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [450,500], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan10rdc.html",
  },
  { atelier:true,
    pro: false,
    gt:false,
    cursus : "Proposé à tous ",
    nom: "CDI",
    exposant: "Centre documentation",
    coords: [450,200], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/cdi.html",

  },
];

