const stands = [
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller vers les batiments 5 et 10",
    nom: "parc",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [600,250], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan10rdc.html",
  },
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller vers le batiment 7",
    nom: "parc",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [950,100], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan7rdc.html",
  },
  {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller vers l'internat",
    nom: "parc",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [950,50], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan9rdc.html",
  }
];

