const stands = [
  {atelier:true,
    pro:true,
    gt:false,
    cursus : "Fillière SANITAIRE",
    nom: "5-109",
    exposant: "Présentation des ateliers sanitaires",
    coords: [200,450], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/sanitaire.html",
  },
  {atelier:true,
    pro:true,
    gt:false,
    cursus : "Classe ULIS",
    nom: "5-105",
    exposant: "Présentation de la classe ULIS",
    coords: [870,450], // y, x en pixels,
    titreInfo:"",
    info:"",
  },
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Fillière Générales et technologique",
    nom: "10-21, 10-22",
    exposant: "Spécialités NSI, SI",
    coords: [870,100], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/si-nsi.html",
  },
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Fillière Générales et technologique",
    nom: "10-27",
    exposant: "Filière STMG et spécialité SES",
    coords: [120,100], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/ses-stmg.html",
  },
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Fillière Générales et technologique",
    nom: "10-26",
    exposant: "Spécialité HGGSP",
    coords: [200,100], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/hggsp.html",
  },
  {atelier:true,
    pro:false,
    gt:true,
    cursus : "Fillière Générales et technologique",
    nom: "10-23",
    exposant: "Option Arts Plastiques",
    coords: [600,100], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/optionarts.html",
  },
  {atelier:true,
    pro:false,
    gt:false,
    cursus : "Pour tous",
    nom: "10-25",
    exposant: "CVL - Corres'Santé",
    coords: [300,100], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/cvlcorres.html",
  },
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller au 2ème étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel",
    coords: [200,550], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan102eme.html",
  },
  {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller au 2ème étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel",
    coords: [900,550], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan102eme.html",
  },
{atelier:false,
    pro:false,
    gt:false,
    cursus : "Retour RDC",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et technologique",
    coords: [450,250], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan10rdc.html",
  }
  
];

