const stands = [
  {atelier:true,
    pro:false,
    gt:false,
    cursus : "En option ou en atelier du midi",
    nom: "Salle Théâtre",
    exposant: "Théâtre",
    coords: [420,300], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/theatre.html",
  },
   {atelier:true,
    pro:false,
    gt:false,
    cursus : "Pour tous",
    nom:"SELF",
    exposant: "SELF - repas chaud",
    coords: [800,150], // y, x en pixels,
    titreInfo:"",
    info:"",
  },
  {atelier:true,
    pro:false,
    gt:false,
    cursus : "Pour tous",
    nom:"CAFETERIA",
    exposant: "CAFET - repas froid",
    coords: [100,250], // y, x en pixels,
    titreInfo:"",
    info:"",
  },
  {atelier:true,
    pro:true,
    gt:false,
    cursus : "CAP EPC",
    nom: "7-01",
    exposant: "Atelier magasin - Commerce",
    coords: [320,150], // y, x en pixels,
    titreInfo:"Plus d'informations",
    info:"../doc/Ateliers/commerce.html",
  },
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller au 2ème étage",
    nom: "Escalier",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [300,220], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan72eme.html",
  },
   {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller vers le Batiment 10",
    nom: "parc",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [420,100], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan10rdc.html",
  },
  {atelier:false,
    pro:false,
    gt:false,
    cursus : "Aller vers l'internat",
    nom: "parc",
    exposant: "Lycée Professionnel - Lycée Général et Technologique",
    coords: [705,200], // y, x en pixels,
    titreInfo:"Accéder",
    info:"../doc/plan9rdc.html",
  }
];

